CREATE TABLE IF NOT EXISTS `users` (
  id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  email varchar(255),
  username varchar(255) NOT NULL,
  password CHAR(64) NOT NULL,
  name varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;